version: "3.6"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  chat-server:
    build: "../ChatServer"
    ports: 
      - "80:80"
    restart: on-failure
    depends_on:
      - rabbitmq
  stock-bot:
    build: "../StockBot"
    restart: on-failure
    depends_on:
      - rabbitmq